version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
    - ./docker-compose/init.sql:/docker-entrypoint-initdb.d/init.sql